force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Cycle Status</label>
    <nameField>
        <label>FYE Cycle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>State Registration</label>
    <nameField>
        <label>Registration  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cycle Status</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Hold for Reg. Acceptance</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCaretingRegistarionPageCont.cls
@isTest
public class TestCaretingRegistarionPageCont {
    
    @isTest
    private static void saveRecord_TGN_TEST(){
        Program__c drProgram_c;
        drProgram_c=new Program__c();
        drProgram_c.Name='Test';
        insert drProgram_c;
        Test.startTest();
        ApexPages.StandardController acController = new ApexPages.StandardController(drProgram_c);
        CaretingRegistarionPageCont obj = new CaretingRegistarionPageCont(acController);
        obj.cbTest=true;
        obj.cbTest1=true;
        obj.cbTest2=true;
        obj.cbTest3=true;
        obj.cbTest4=true;
        obj.cbTest5=true;
        obj.cbTest6=true;
        obj.cbTest7=true;
        obj.cbTest8=true;
        obj.cbTest9=true;
        obj.cbTest10=true;
        obj.cbTest11=true;
        obj.cbTest12=true;
        obj.cbTest13=true;
        obj.cbTest14=true;
        obj.cbTest15=true;
        obj.cbTest16=true;
        obj.cbTest17=true;
        obj.cbTest18=true;
        obj.cbTest19=true;
        obj.cbTest20=true;
        obj.cbTest21=true;
        obj.cbTest22=true;
        obj.cbTest23=true;
        obj.cbTest24=true;
        obj.cbTest25=true;
        obj.cbTest26=true;
        obj.cbTest27=true;
        obj.cbTest28=true;
        obj.cbTest29=true;
        obj.cbTest30=true;
        obj.cbTest31=true;
        obj.cbTest32=true;
        obj.cbTest33=true;
        obj.cbTest34=true;
        obj.cbTest35=true;
        obj.cbTest36=true;
        obj.cbTest37=true;
        obj.cbTest38=true;
        obj.cbTest39=true;
        obj.cbTest40=true;
        obj.cbTest41=true;
        obj.cbTest42=true;
        obj.cbTest43=true;
        obj.cbTest44=true;
        obj.cbTest45=true;
        obj.cbTest46=true;
        obj.cbTest47=true;
        obj.cbTest48=true;
        obj.cbTest49=true;
        obj.cbTest50=true;
        /*
Registration__c rr= new Registration__c();
rr.name=drProgram_c.name+' '+'Alabama';
rr.Program__c=drProgram_c.id;
rr.Status__c='New';
rr.State__c='Alabama';*/
        
        obj.saveRecord();
        Test.stopTest();
    }
}