force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Cycle Status</label>
    <nameField>
        <label>FYE Cycle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>State Registration</label>
    <nameField>
        <label>Registration  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <description>Formula field to show related owner Full name</description>
    <formula>Owner:User.FirstName + &quot; &quot;+Owner:User.LastName</formula>
    <label>Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cycle Status</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Health__c.field-meta.xml
<CustomField>
    <fullName>Registration_Health__c</fullName>
    <formula>IMAGE( 
CASE( Status__c , 
&quot;Completed&quot;, &quot;/img/samples/flag_green.gif&quot;,
&quot;New&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Submitted&quot;, &quot;/img/samples/flag_yellow.gif&quot;, 
&quot;Processing&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Pending&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Hold for Reg. Acceptance&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
&quot;Rejected&quot;, &quot;/img/samples/flag_red.gif&quot;,
&quot;/s.gif&quot;), 
&quot;Priority Flag&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Health</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Hold for Reg. Acceptance</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/contenVersionFilePreview.cls
/*
 * Test Class Name:-TestcontenVersionFilePreview
 */ 
public class contenVersionFilePreview {
    @AuraEnabled(cacheable = true)
    //public Static  List<ContentVersion> cvRecords2(String recId){
    public Static  List<Registration__c> cvRecords2(String recId){
        set<Id> SetIds = new Set<id>();
        List<Registration__c> resList =[select id,name, Status__c,Program__c,State__c,Owner.LastName,Owner_Name__c,Registration_Health__c,
										Start_Date__c,End_Date__c from Registration__c where Program__c=:recId];
        return resList;
	}
}