force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answers for FAQ</description>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TestFAQControllerDynamic.cls
@isTest
public class TestFAQControllerDynamic {
    @isTest static void method1(){
        Knowledge__kav newArticle = new Knowledge__kav();
        newArticle.Title = 'test';
        newArticle.UrlName= 'test';
        newArticle.Question__c='Test WC&B';
        newArticle.Answer__c='Test WC&B';
        newArticle.Language = 'en_US';  
        insert newArticle;
        KbManagement.PublishingService.publishArticle([select id,KnowledgeArticleId from Knowledge__kav where id=:newArticle.Id].KnowledgeArticleId, true);
        FAQControllerDynamic.getFAQArticle();
        //FAQControllerDynamic.getKavMin();
    }

}